### ISSUE TITLE
Can not detect request in subcollection 

### ISSUE THREAD

**Issue by sakacyber** [Elhussein-Hamed/PostmanToRetrofit2-v2#2]
You do a great job. The library works well with a simple postman collection but can not parse with requests in subcollection like group requests in a folder. Thanks.

**Comment by Elhussein-Hamed** [comment]
@sakacyber Thanks for your kind words. :) 

I have added the support for subcollections, it will be available in the next release.

**Comment by Elhussein-Hamed** [comment]
This has been fixed in release v1.3.0.
