### ISSUE TITLE
Update to the new intellij version

### ISSUE THREAD

**Issue by mdu39170** [Elhussein-Hamed/PostmanToRetrofit2-v2#7]
Hi,

can you update your plugin please ? 
I need it to save time.

thanks a lot

**Comment by Elhussein-Hamed** [comment]
@mdu39170 Thanks for your comment. I have updated the plugin, a new version will be released in the marketplace soon.

**Comment by Elhussein-Hamed** [comment]
@mdu39170 v2.0.0 is released supporting new IDE versions.
